sudo: false
language: node_js
node_js:
  - 8
  - 9
  - 10
  - stable

cache:
  bundle: true
  directories:
    - node_modules

jobs:
  include:
  - stage: Document deploy
    node_js: 9
    allow_failure: true
    script: npm run build:example
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
      local_dir: public

#  - stage: Test
#    node_js: 9
#    before_script: npm install codecov
#    script: npm test -- --coverage
#    after_script: codecov --token=$CODECOV_TOKEN
